// Import embeddings statically for Cloudflare Workers compatibility
import storedEmbeddingsData from "@/data/embeddings/resume-embeddings.json";

interface EmbeddingResult {
	content: string;
	similarity: number;
	source: string;
}

interface StoredEmbedding {
	content: string;
	embedding: number[];
	source: string;
}

// Cast imported data to proper type
const storedEmbeddings: StoredEmbedding[] = storedEmbeddingsData as StoredEmbedding[];

// Note: generateEmbeddings is only available via the CLI script (scripts/generate-embeddings.ts)
// It cannot be used at runtime in Cloudflare Workers due to filesystem access limitations

const STOP_WORDS = new Set([
	"a",
	"about",
	"and",
	"are",
	"as",
	"at",
	"based",
	"be",
	"for",
	"from",
	"has",
	"have",
	"how",
	"in",
	"is",
	"it",
	"kirill",
	"me",
	"of",
	"on",
	"or",
	"so",
	"that",
	"the",
	"this",
	"to",
	"what",
	"with",
	"you",
]);

function tokenize(text: string): string[] {
	return (
		text
			.toLowerCase()
			.replace(/<[^>]*>/g, " ")
			.match(/[a-z0-9]+/g)
			?.filter((token) => token.length > 2 && !STOP_WORDS.has(token)) ?? []
	);
}

function lexicalSimilarity(queryTokens: string[], content: string): number {
	if (queryTokens.length === 0) return 0;

	const contentTokens = new Set(tokenize(content));
	let matches = 0;

	for (const token of queryTokens) {
		if (contentTokens.has(token)) matches += 1;
	}

	return matches / queryTokens.length;
}

export async function findSimilarContent(query: string): Promise<EmbeddingResult[]> {
	const queryTokens = tokenize(query);

	try {
		// Filter out embeddings without sources
		const validEmbeddings = storedEmbeddings.filter((e) => e.source);
		console.log(
			"Found stored embeddings:",
			validEmbeddings.map((e) => e.source),
		);

		// Use lexical ranking at runtime. Stored vectors were generated by an older
		// embedding model, so mixing them with a new query model would be unreliable.
		const similarities: EmbeddingResult[] = validEmbeddings.map((stored) => ({
			content: stored.content,
			similarity: lexicalSimilarity(queryTokens, stored.content),
			source: stored.source,
		}));

		// Sort by similarity and get top 5
		const results = similarities.sort((a, b) => b.similarity - a.similarity).slice(0, 5);

		console.log(
			"Top matches:",
			results.map((r) => ({ source: r.source, similarity: r.similarity })),
		);
		return results;
	} catch (error) {
		console.error("Error finding similar content:", error);
		throw error;
	}
}
